# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 陈鑫磊的博客
subtitle: ''
description: '陈鑫磊的博客'
keywords: 
  - 陈鑫磊的博客
  - cxl2020mc
  - cxl2020MC
author: 陈鑫磊
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.cxl2020mc.top
# permalink: :year/:month/:day/:title/
permalink: post/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
# updated_option: 'mtime'
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  # type: git
  # repo:
    # gitHub: https://cxl2020MC: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@github.com/cxl2020MC/cxl2020MC.github.io.git,master
    # gitee: https://[GiteeUsername]:[GiteeToken]@gitee.com/[GiteeUsername]/[GiteeBlogRepo].git[,branch]
    # coding: https://[TokenUser]:[CodingToken]@e.coding.net/[CodingUsername]/[CodingBlogRepo].git[,branch]
  # [,branch]为可选项，表示部署的分支
  #2020年10月后github新建仓库默认分支改为main
  type: git
  repo: https://cxl2020MC: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@github.com/cxl2020MC/cxl2020MC.github.io.git #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io
  branch: master
  # message: [message]

search:
  path: search.xml
  field: all
  content: true

feed:
  enable: true
  # Generate both atom and rss2 feeds
  type:
    - atom
    - rss2
  path:
    - atom.xml
    - rss2.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# HexoPlusPlus Talk
# see https://hexoplusplus.js.org
hpptalk:
  enable: true 
  domain: plusplus.cxl2020mc.workers.dev
  path:
  limit:
  start:
  js:
  css:
  option:
  front_matter:

sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  # template: ./sitemap_template.xml
  # template_txt: ./sitemap_template.txt
  rel: false
  tags: true
  categories: true


encrypt: # hexo-blog-encrypt
  abstract: 有东西被加密了, 请输入密码查看.
  message: 您好, 这里需要密码.
  # tags:
    # - {name: tagName, password: 密码A}
    # - {name: tagName, password: 密码B}
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true #开关插件版看板娘
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://npm.elemecdn.com/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  dialog:
    enable: true # 显示对话框人物显示对话框
    # hitokoto: true # 启用 hitokoto 使用一言API
  model:
    use: https://cxl2020mc-1304820025.file.myqcloud.com/wives/snow_miku/model.json # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://npm.elemecdn.com/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  display:
    position: right #控制看板娘位置
    width: 300 #控制看板娘大小
    height: 300 #控制看板娘大小
    hOffset: 0
    vOffset: -20 # -20
  mobile:
    show: true # 手机中是否展示
    scale: 0.5 # 0.5

# hexo-offline-popup.
service_worker:
  maximumFileSizeToCacheInBytes: 15145728 # 缓存的最大文件大小，以字节为单位，此处设置为3MB。(3145728)
  staticFileGlobs:
    - public/**/*.{js,html,xml,css,png,jpg,gif,svg,webp,eot,ttf,woff,woff2}
    # - public/**/*.{html,xml} #精简版使用这行即可
  # 静态文件合集，如果你的站点使用了例如webp格式的文件，请将文件类型添加进去。。
  # 注意，此处的文件类型就是会缓存下来的所有文件类型，如果不需要缓存那么多，
  # 而只是想判断网页更新与否，缓存html和xml即可。
  stripPrefix: public
  verbose: false
  runtimeCaching:
    # CDNs - should be cacheFirst, since they should be used specific versions so should not change
    - urlPattern: /* # 如果你需要加载CDN資源，请配置该选项，如果沒有，可以不配置。
      handler: cacheFirst
      options:
        origin: unpkg.com # 又拍云
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net # jsdelivr
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.cxl2020mc.top
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cxl2020mc-1304820025.file.myqcloud.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: api.cxl2020mc.top
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cn.bing.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: gravatar.cxl2020mc.top # 头像
        
    # 更多cdn可自行参照上述格式进行配置。