name: ClientWorker 
catch_rules:
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/npm|jsd\.cxl2020mc\.top\/npm)
    transform_rules:
      - search: _
        replace:
          - https://jsd.cxl2020mc.top/npm
          - https://vercel.jsd.cxl2020mc.top/npm
          - https://unpkg.com
          - https://repo.huaweicloud.com/repository/npm/
          - _
        action: fetch
        fetch:
          status: 200
          engine: parallel
          preflight: false
          timeout: 5000
          cache:
            expire: 1000*60*60*24
            delay: 200
  # 不劫持（丢给浏览器）
  - rule: .*
    transform_rules:
      - search: .*
        action: skip     #? 2.8.1新增，跳过cw规则