# https://clientworker.js.org/
name: ClientWorker 
cleaninterval: 1000*30 # 每30秒检测并清理一次缓存
# ClientWorker热补丁
hotpatch:
  - https://jsd.cxl2020mc.top/npm/clientworker@latest
  - https://raw.githubusercontent.com/ChenYFan/ClientWorker/gh-pages/cw.js
  - https://cdn.jsdelivr.net/gh/ChenYFan/ClientWorker/cw.js
# Config热更新
hotconfig:
  - https://github.com/cxl2020MC/cxl2020MC.github.io/raw/master/source/config.yaml
  - https://raw.githubusercontent.com/cxl2020MC/cxl2020MC.github.io/master/source/config.yaml
catch_rules:
  # 并发博客
  - rule: _
    transform_rules:
      - search: _
        replace:
          - www.cxl2020mc.top
          # - netlify.cxl2020mc.top #会带来cors问题
          - cfpage.cxl2020mc.top
          - cdn.vercel.cxl2020mc.top
          - _
        action: fetch
        fetch:
          status: .*
          engine: parallel
          preflight: false # false
          timeout: 30000
  # npm加速
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/npm|unpkg\.com|jsd\.cxl2020mc\.top\/npm)
    transform_rules:
      - search: _
        replace:
          - https://jsd.cxl2020mc.top/npm
          - https://vercel.jsd.cxl2020mc.top/npm
          - https://unpkg.cnortles.top
          - https://cdn.cnortles.top/npm
          - https://project.cnortles.top/proxy/jsdelivr/npm
          - https://jsdelivr.pai233.top/npm
          - https://cdn.jsdelivr.net/npm
          - https://unpkg.com
          # - https://repo.huaweicloud.com/repository/npm/
          - _
        action: fetch
        fetch:
          status: 200|304 # 304状态码，表示自上次访问以来，请求的资源未被修改。该状态码较少出现，所以基本没啥卵用(大文件除外)
          engine: parallel
          preflight: false # false
          timeout: 30000
          cache:
            expire: 1000*60*60*8 # 缓存8小时
            delay: 300
  # github加速
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/gh|jsd\.cxl2020mc\.top\/gh)
    transform_rules:
      - search: _
        replace:
          - https://jsd.cxl2020mc.top/gh
          - https://vercel.jsd.cxl2020mc.top/gh
          - https://cdn.cnortles.top/gh
          - https://project.cnortles.top/proxy/jsdelivr/gh
          - https://jsdelivr.pai233.top/gh
          - https://cdn.jsdelivr.net/gh
          - _
        action: fetch
        fetch:
          status: 200|304
          engine: parallel
          preflight: false # false
          timeout: 30000
          cache:
            expire: 1000*60*60*8 # 缓存8小时
            delay: 300
  - rule: ^https\:\/\/cxl2020mc-1304820025\.file\.myqcloud\.com
    transform_rules:
      - search: _
        action: fetch
        fetch:
          status: .*
          engine: fetch
          preflight: true # false
          timeout: 50000
          cache:
            expire: 1000*60*5 # 缓存5分钟
            delay: 300
  # api图片缓存
  - rule: ^https\:\/\/api\.cxl2020mc\.top
    transform_rules:
      - search: _
        action: fetch
        fetch:
          status: .*
          engine: fetch
          preflight: true # false
          timeout: 50000
          cache:
            expire: 1000*60*60 # 缓存60分钟
            delay: 300
  # 不劫持（丢给浏览器）
  - rule: .*
    transform_rules:
      - search: _
        action: skip #? 2.8.1新增，跳过cw规则（ 现在已经不在需要）