# 自动更新js https://jsd.cxl2020mc.top/npm/clientworker/dist/autoupdate.js
name: ClientWorker 
catch_rules:
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/npm)
    transform_rules:
      - search: _
        replace:
          - _
          - https://jsd.cxl2020mc.top/npm
          - https://vercel.jsd.cxl2020mc.top/npm
          - https://unpkg.com
